### ISSUE TITLE
404 page error / german GEMA

### ISSUE THREAD

**Issue by foorb** [Kikobeats/uno-zen#106] opened 2015-10-12 06:19 UTC
I really like the 404 page. The panic button is also very funny.
But in germany - there is the GEMA. They block this video:
![bildschirmfoto 2015-10-12 um 08 01 56](https://cloud.githubusercontent.com/assets/14993807/10422258/323414fc-70b8-11e5-82f5-b54acdadb08c.png)
Maybe we can find something else. Something that doesn't need too much bandwith. 
I know everyone can change the button, but something that work for everyone by default would be nice.
Any suggestions?

**Comment by Kikobeats** [comment] 2015-10-12 09:08
dam! I suppose that we need to embed another youtube video with copyright 😐

**Comment by foorb** [comment] 2015-10-26 12:46
Maybe theres something more lightweight than a youtube video? Like:
https://github.com/notwaldorf/emoji-rain - [Demo](http://meowni.ca/emoji-rain/)
or a simple gif:
https://media.giphy.com/media/lKZEeXJGhU1d6/giphy.gif

**Comment by Kikobeats** [comment] 2015-10-26 16:26
The problem is that currently we have many JS and CSS around 404. I love emoji rain, but change this part of the project cost the same that make a blog refactor and I feel that I need to support other issues first.

I'm sorry but I have to close this issue to maintain common points of the project. Of course feel free to implement in your personal fork. (and show me when you do it, please)

Why GEMA, WHY.

**Closed as completed by Kikobeats** 2015-10-26 16:26 UTC
Labels: wontfix
